import { Navigation, Zap, Trash2 } from "react-feather";

export const dataMisi = [
  {
    mobilitasHijau: [
      {
        judul: "Ekspedisi Gowes Pagi",
        deskripsi: "Gunakan sepeda untuk perjalananmu hari ini, baik ke sekolah, kantor, atau sekadar berkeliling komplek.",
        point: 30,
        kategori: "Mobilitas Hijau",
        icon: "Navigation",
        typeColor: "text-green-400",
        borderColor: "border-green-400",
      },
      {
        judul: "Quest Pejalan Kaki",
        deskripsi: "Pilih berjalan kaki untuk mencapai tujuan jarak dekat (di bawah 1 km) daripada menggunakan kendaraan bermotor.",
        point: 20,
        kategori: "Mobilitas Hijau",
        icon: "Navigation",
        typeColor: "text-green-400",
        borderColor: "border-green-400",
      },
      {
        judul: "Jelajah Halte Terdekat",
        deskripsi: "Selesaikan satu perjalanan menggunakan transportasi umum seperti bus, angkot, atau KRL.",
        point: 40,
        kategori: "Mobilitas Hijau",
        icon: "Navigation",
        typeColor: "text-green-400",
        borderColor: "border-green-400",
      },
      {
        judul: "Misi Bebas Asap",
        deskripsi: "Berhasil melalui satu hari penuh tanpa menyalakan atau menaiki kendaraan pribadi (mobil/motor).",
        point: 50,
        kategori: "Mobilitas Hijau",
        icon: "Navigation",
        typeColor: "text-green-400",
        borderColor: "border-green-400",
      },
    ],
    hematEnergi: [
      {
        judul: "Operasi Senyap Elektronik",
        deskripsi: "Cabut minimal 3 colokan elektronik (charger, TV, kipas) yang sedang tidak terpakai dari stop kontak.",
        point: 15,
        kategori: "Hemat Energi",
        icon: "Zap",
        typeColor: "text-yellow-400",
        borderColor: "border-yellow-400",
      },
      {
        judul: "Misi Ksatria Cahaya",
        deskripsi: "Pastikan semua lampu di ruangan yang kosong sudah dimatikan sebelum kamu meninggalkannya.",
        point: 10,
        kategori: "Hemat Energi",
        icon: "Zap",
        typeColor: "text-yellow-400",
        borderColor: "border-yellow-400",
      },
      {
        judul: "Jurus Mandi Cepat",
        deskripsi: "Tantang dirimu untuk mandi di bawah 10 menit guna menghemat air dan energi pemanas (jika ada).",
        point: 20,
        kategori: "Hemat Energi",
        icon: "Zap",
        typeColor: "text-yellow-400",
        borderColor: "border-yellow-400",
      },
      {
        judul: "Tantangan Tanpa AC",
        deskripsi: "Berhasil melewati 2 jam di siang hari tanpa menyalakan AC, cukup gunakan kipas atau jendela.",
        point: 25,
        kategori: "Hemat Energi",
        icon: "Zap",
        typeColor: "text-yellow-400",
        borderColor: "border-yellow-400",
      },
    ],
    kebersihan: [
      {
        judul: "Tantangan Tas Juara",
        deskripsi: "Lakukan aktivitas belanja tanpa meminta atau menggunakan kantong plastik sama sekali.",
        point: 25,
        kategori: "Kebersihan & Konsumsi",
        icon: "Trash2",
        typeColor: "text-red-400",
        borderColor: "border-red-400",
      },
      {
        judul: "Misi Botol Abadi",
        deskripsi: "Bawa dan isi ulang botol minummu sendiri sepanjang hari, hindari membeli air kemasan plastik.",
        point: 20,
        kategori: "Kebersihan & Konsumsi",
        icon: "Trash2",
        typeColor: "text-red-400",
        borderColor: "border-red-400",
      },
      {
        judul: "Misi Tiga Warna",
        deskripsi: "Pastikan kamu telah memilah sampah di rumahmu ke dalam tiga kategori: organik, anorganik, dan B3.",
        point: 35,
        kategori: "Kebersihan & Konsumsi",
        icon: "Trash2",
        typeColor: "text-red-400",
        borderColor: "border-red-400",
      },
      {
        judul: "Operasi Pungut Sampah",
        deskripsi: "Ambil dan buang minimal 3 sampah plastik yang kamu temukan di jalan atau fasilitas umum ke tempat sampah.",
        point: 15,
        kategori: "Kebersihan & Konsumsi",
        icon: "Trash2",
        typeColor: "text-red-400",
        borderColor: "border-red-400",
      },
    ],
  },
];